[WIP]HOME,PROFILE画面の実装
Rick-32/booklog pull request #6
Opened 2019-03-09 22:39 UTC by Rick-32

#WHAT
ログイン後のユーザーのHOME画面とPROFILE画面を実装する

#WHY
ログインしたユーザーが、自分の本の登録状況やプロフィールの内容を確認・編集できるようにするため

2019-03-22 02:03 UTC, miyagit reviewed
全体的にインデントが４つになってるので２つに統一しましょう。

2019-03-22 02:03 UTC, miyagit commented on app/controllers/users_controller.rb
> +		@user = User.find(params[:id])
set_でまとめましょう。

2019-03-22 02:03 UTC, miyagit commented on app/models/user.rb
> +	enum prefecture: {
こちらはactive_hashを使いましょう。

2019-03-22 23:02 UTC, Rick-32 commented
> 全体的にインデントが４つになってるので２つに統一しましょう。

レビューありがとうございます！こちら、昨晩からずっと見ていましたがインデントの設定は２になっていました。指摘されたことと自分の捉え方に誤解があるかもと思い、もしかしたらの可能性なのですが。。

edit.html.erbなど、今実装しているビューファイルの多くは、レイアウトファイルの<%= yield %>部分にあたるため、「レイアウトファイルに直接edit〜の中身を書いていたら、ファイルの書き出し部分のインデントは４つ下がっているはず」と考えてインデントが４つ（tabキー２つ分）としています。
これはつまり、<%= yield %>で切り離してかき分けたファイルの中身は、書き出しをインデントせずに初めから詰めて書いてよかったということでしょうか？

2019-03-23 03:59 UTC, Rick-32 commented on app/models/user.rb
> +	enum prefecture: {
こちらはなぜこのgemを用いることをお勧めされたかの理由を調べている最中なので、まだ着手していません。

2019-03-23 04:05 UTC, yuki-uchida commented
> 全体的にインデントが４つになってるので２つに統一しましょう。
こちらはインデントを2スペースに変換するようにエディタ側で設定しましょう。file_changedを見ればわかるように、非常に見辛いです

2019-03-23 04:07 UTC, Rick-32 commented on app/controllers/users_controller.rb
> +		@user = User.find(params[:id])
修正しました。

2019-03-23 04:07 UTC, yuki-uchida commented
>書き出しをインデントせずに初めから詰めて書いてよかったということでしょうか？


そうなります。ちょっと理解ができてないのですが、ファイルの先頭にtabを入れる理由がわかりません。

2019-03-23 04:08 UTC, yuki-uchida commented
active_hashの実装も忘れずにお願いします

2019-03-23 23:05 UTC, Rick-32 commented on app/models/user.rb
> +	enum prefecture: {
確認して実装しました。

2019-03-24 02:18 UTC, yuki-uchida requested changes
aタグは全てlink＿toで記述しましょう

2019-03-24 02:18 UTC, yuki-uchida commented on app/assets/stylesheets/modules/_home.scss
> +	display: inline-block;
.user-naviの方にネストする形で入れましょう

2019-03-24 02:18 UTC, yuki-uchida commented on app/models/user.rb
> +	enum prefecture: {
こちらpush忘れてませんか？

2019-03-24 02:38 UTC, Rick-32 commented on app/assets/stylesheets/modules/_home.scss
> +	display: inline-block;
aタグで書いてあるものは実装しないことになっているダミーのリンク関係なのですが、それもlink_toでということでしょうか？

2019-03-24 02:45 UTC, Rick-32 commented on app/assets/stylesheets/modules/_home.scss
> +	display: inline-block;
user-naviにネストは行いました。

2019-03-24 02:48 UTC, yuki-uchida commented
実装しないというのは「本プルリクでは」ということでしょうか？それとも今後も使わないということでしょうか？
今後も使わないのであれば消していただきたいですが...

今後の方針を教えてください。

2019-03-24 02:52 UTC, Rick-32 commented on app/models/user.rb
> +	enum prefecture: {
忘れていました。すみません。pushしておきました。

2019-03-24 02:53 UTC, yuki-uchida requested changes
BEMに沿ってCSSを書くのであればほぼ全てがネストする形で書かれます

2019-03-24 02:53 UTC, yuki-uchida commented on app/assets/stylesheets/config/_base.scss
>  .l5M {
BEMに沿った形でクラス命名をするのであれば、良く使うCSSはクラス付与する形で適応するのではなく、mixinで必要なところに呼び出す形にしてください

2019-03-24 02:53 UTC, yuki-uchida commented on app/assets/stylesheets/config/_base.scss
>  .l5M {
BEMでは複数のクラスはあまりつけないためです。

どの要素に何のCSSが設定されているか一目瞭然にするためです

2019-03-24 02:53 UTC, yuki-uchida commented on app/assets/stylesheets/modules/_home.scss
> +.clearfix:after {
これもmixinで

2019-03-24 02:53 UTC, yuki-uchida commented on app/assets/stylesheets/modules/_home.scss
> +.user__info {
これも親要素にネストする形で書いてください

2019-03-24 02:55 UTC, Rick-32 commented
担当ライフコーチとの実装完了の定義では、
・リンクの中身を実装せず、見た目は見本サイトと同じようにする
・リンク先も含めて実装する
の２種類があり、前者についてはaタグで書いて良いか確認した際に大丈夫という回答だったので、そのような形になりました。

2019-03-26 08:39 UTC, TOMARUMARU commented
リンク先がないダミーのリンクであってもaタグをlink_toに直すことに問題はないと思います。そこまで手間でもないので..

2019-03-26 08:43 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
current_userはviewでも使えるので変数に入れる必要はないかと

2019-03-26 08:43 UTC, TOMARUMARU commented on config/routes.rb
> +	get '/logout' 				=> "users#logout", as: :logout
resources :usersにネストしましょう。

2019-03-26 08:43 UTC, TOMARUMARU commented on config/routes.rb
> +	get '/profile' 				=> "users#show", as: :profile
こちらも

2019-03-26 08:43 UTC, TOMARUMARU commented on config/routes.rb
> +	resources :users do
12行目とまとめましょう

2019-03-26 08:44 UTC, TOMARUMARU reviewed
全体的にインデントがかなりぐちゃぐちゃなのですが、Files Changedを確認して修正いただけますか？

2019-03-26 09:53 UTC, Rick-32 commented on config/routes.rb
> +	get '/logout' 				=> "users#logout", as: :logout
ネストしました。

2019-03-26 09:54 UTC, Rick-32 commented on config/routes.rb
> +	get '/profile' 				=> "users#show", as: :profile
ネストしました。

2019-03-26 09:54 UTC, Rick-32 commented on config/routes.rb
> +	resources :users do
まとめました。

2019-03-26 10:05 UTC, Rick-32 commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
> 全体的にインデントがかなりぐちゃぐちゃなのですが、Files Changedを確認して修正いただけますか？



> 全体的にインデントがかなりぐちゃぐちゃなのですが、Files Changedを確認して修正いただけますか？

Git上ではタブが８つになっていてインデントがぐちゃぐちゃなファイルがあるのですが、実際のファイルは揃っています。この表記はどうすれば実際と同じになるかわかりませんでした。

2019-03-26 10:05 UTC, Rick-32 commented on app/assets/stylesheets/config/_base.scss
>  .l5M {
WHATの部分に追記しました。

2019-03-26 10:05 UTC, Rick-32 commented on app/assets/stylesheets/modules/_home.scss
> +.clearfix:after {
WHATの部分に追記しました。

2019-03-26 10:06 UTC, Rick-32 commented on app/assets/stylesheets/modules/_home.scss
> +.user__info {
WHATの部分に追記しました。

2019-03-26 10:36 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
current_userに関しては、viewでも使えるので、わざわざcontrollerで変数に入れてviewで変数展開するのが二度手間では？という意味です。

2019-03-26 10:38 UTC, TOMARUMARU reviewed
インデントの件はトレーナーより説明を受けたので大丈夫です！

2019-03-26 10:38 UTC, TOMARUMARU commented on config/routes.rb
> +	get '/profile' 				=> "users#show", as: :profile
これら二つもresources :usersにネストさせましょう

2019-03-26 10:42 UTC, Rick-32 commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
controllerに書かずにviewのリンク先で設定しても思った結果になりませんでした。

2019-03-26 10:53 UTC, Rick-32 commented on config/routes.rb
> +	get '/profile' 				=> "users#show", as: :profile
resources :users, only: [:edit, :update, :destroy ] do
		collection do
			get :profile
			get :home
		end
	end
	get '/logout' 				=> "users#logout", as: :logout
	get '/profile' 				=> "users#show", as: :profile
end

これはネストになっていないということですよね。

	resources :users, only: [:index, :edit, :update, :destroy ] do
		collection do
			get :profile
			get :home
		end
		get '/logout' 				=> "users#logout", as: :logout
		get '/profile' 				=> "users#show", as: :profile
	end

のようにネストさせようとすると、ログアウト時にundefined local variable or method `logout_path'のエラーが出て、logout_pathが効かなくなります。logoutだけ外して書いても良いのでしょうか？

2019-03-26 10:56 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
どのようなエラーを吐くのか教えてください

2019-03-26 10:57 UTC, TOMARUMARU commented on config/routes.rb
> +	get '/profile' 				=> "users#show", as: :profile
collectionの中にネストしていないからではないですか？またpathが多少変わるかもしれないのでrake routesで確認してください

2019-03-26 11:03 UTC, Rick-32 commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
ActiveRecord::RecordNotFound at /users/profile.12
Couldn't find User without an IDとなり、users_controllerで書き換えた
	def set_user
		@user = User.find(params[:id])
	end
のparams[:id]の中身を見るとnilが返ってきています。

2019-03-26 11:07 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
なぜ```@user = User.find(params[:id])```
に書き換えたのでしょう？
set_userというメソッド自体が不要になります

2019-03-26 11:17 UTC, Rick-32 commented on config/routes.rb
> +	get '/profile' 				=> "users#show", as: :profile
ネストの修正行いました。

2019-03-26 11:20 UTC, Rick-32 commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
users_controllerでは、ユーザーのマイページやユーザーのプロフィールをログインしたユーザー自身が行うためのアクションを制御する目的で設定していたので、フィルターとして特定のアクションの際に、ログインしているユーザーをセットする意図で記述しました。

2019-03-26 11:22 UTC, Rick-32 commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
結論として、set_userというフィルターはここではなくても動作に影響がないということでしょうか。

2019-03-26 11:25 UTC, yusukeyamane commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
@user = User.find(current_user.id)
であれば
@user = current_user
でいいと思います。findで走るクエリがもったいないので（current_userを取得した段階でクエリが走っています。）

2019-03-26 11:27 UTC, yusukeyamane commented on app/models/user.rb
> +	extend ActiveHash::Associations::ActiveRecordExtensions
インデント深すぎると思います！

2019-03-26 11:27 UTC, yusukeyamane commented on app/models/user.rb
> +	enum gender: {
インデント深すぎると思います！

2019-03-26 11:27 UTC, yusukeyamane commented on app/models/gender.rb
> +end
改行しましょう

2019-03-26 11:28 UTC, yusukeyamane commented on app/views/users/edit.html.erb
> +									<strong class="r10M"><%= @user.user_id %></strong>
@user.id
ではないのですか？エラーになっていませんか？

2019-03-26 11:33 UTC, Rick-32 commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
そういうことだったのですね。認識の確認です。

>>current_userに関しては、viewでも使えるので、わざわざcontrollerで変数に入れてviewで変数展開するのが二度手間では？
というのは、current_userを用いること自体に対してではなく、
@user = current_userと記述した時点でクエリが走って期待するユーザーを参照できているのに、findを使ってわざわざcurrent_userにクエリを走らせることが同じ処理の要求を二重に行なっていることになるので省くことを勧める、という意味でよかったでしょうか？

2019-03-26 11:37 UTC, Rick-32 commented on app/models/user.rb
> +	extend ActiveHash::Associations::ActiveRecordExtensions
上記に同様のやり取りがあるのですが、なぜか僕のコメントが削除されているので再掲します

>実際のコードではインデントを2マスで付けているのですが、github上だと8つでインデントがついてしまいます。
認識ではインデントは揃えているのつもりなのですが、こちらはgithubの設定が問題でしょうか？

それに対してレビュワーの方も

>インデントの件はトレーナーより説明を受けたので大丈夫です！

というやり取りがありました。実際はインデントは問題ないです。

2019-03-26 11:37 UTC, Rick-32 commented on app/models/user.rb
> +	enum gender: {
上記に同様のやり取りがあるのですが、なぜか僕のコメントが削除されているので再掲します

>実際のコードではインデントを2マスで付けているのですが、github上だと8つでインデントがついてしまいます。
認識ではインデントは揃えているのつもりなのですが、こちらはgithubの設定が問題でしょうか？

それに対してレビュワーの方も

>インデントの件はトレーナーより説明を受けたので大丈夫です！

というやり取りがありました。実際はインデントは問題ないです。

2019-03-26 11:43 UTC, Rick-32 commented on app/views/users/edit.html.erb
> +									<strong class="r10M"><%= @user.user_id %></strong>
これは僕の命名がわるかったのですがuser_idとnameというカラムがあり、ブクログIDというのはユーザーが新規登録時にパスワードと共に設定するユーザーID、nameがニックネームでレビューやコメントを書いた際に表示されるものになります。
ですので、ここはエラーになっておらず、表示もあっています。

2019-03-26 11:45 UTC, yusukeyamane commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
> findを使ってわざわざcurrent_userにクエリを走らせることが同じ処理の要求を二重に行なっていることになるので省くことを勧める

これです！

2019-03-26 11:45 UTC, yusukeyamane commented on app/models/user.rb
> +	extend ActiveHash::Associations::ActiveRecordExtensions
承知しました！

2019-03-26 11:45 UTC, yusukeyamane commented on app/models/user.rb
> +	enum gender: {
承知しましたです！

2019-03-26 11:47 UTC, Rick-32 commented on app/controllers/users_controller.rb
> +		@user = User.find(current_user.id)
理解しました！ありがとうございます！

2019-03-26 11:48 UTC, Rick-32 commented on app/models/gender.rb
> +end
改行しました

2019-03-26 11:48 UTC, yusukeyamane commented on app/views/users/edit.html.erb
> +									<strong class="r10M"><%= @user.user_id %></strong>
承知しました。たぶん、毎回該当箇所指摘されてしまうと思うのでカラム名はこの段階で変更して頂いてもいいのかなと思います....

2019-03-26 11:51 UTC, Rick-32 commented on app/views/users/edit.html.erb
> +									<strong class="r10M"><%= @user.user_id %></strong>
そのままbooklog-idのような感じで良いですかね…ネーミングセンスが悪いので気をつけたいと思います。

2019-03-26 12:06 UTC, Rick-32 commented on app/views/users/edit.html.erb
> +									<strong class="r10M"><%= @user.user_id %></strong>
use_id修正しました

2019-03-26 12:10 UTC, yusukeyamane commented on app/views/users/edit.html.erb
> +									<strong class="r10M"><%= @user.user_id %></strong>
booklog_idもしくはuid(unique id)かなと思います。今回は前者なので良いかと

2019-03-26 12:10 UTC, yusukeyamane commented
お疲れ様でした！LGTMです〜

2019-03-26 12:11 UTC, Rick-32 commented on app/views/users/edit.html.erb
> +									<strong class="r10M"><%= @user.user_id %></strong>
booklog_idに修正済みです

2019-03-26 12:12 UTC, merged